apiVersion: v1
kind: Service

metadata:
  name: python-demo-service

spec:
  type: NodePort

  selector:
    app: python-demo

  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30007